version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 605134457967.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t agent .
      - docker tag agent:latest 605134457967.dkr.ecr.us-east-1.amazonaws.com/agent_codes:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 605134457967.dkr.ecr.us-east-1.amazonaws.com/agent_codes:latest
      - echo Build completed successfully.



